name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Dictionaries Test
      id: dictionaries-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Dictionaries Test
        setup-command: ''
        command: python test_script.py
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DICTIONARIES-TEST_RESULTS: "${{steps.dictionaries-test.outputs.result}}"
      with:
        runners: dictionaries-test
